version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo 'hello'
      - aws s3 cp code/ s3://amcarow --recursive --metadata GIT_SHA=$CODEBUILD_SOURCE_VERSION
