version: 0.2

phases:
  install:
    runtime-version:
      python: 3.7
  build:
    commands:
      - echo 'hello'
      - aws s3 cp nested_templates/ s3://$TA_S3_NAME/nested_templates --recursive --metadata GIT_SHA=$CODEBUILD_SOURCE_VERSION
